name: Budgematic CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Run Linter
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint

  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Run Tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: ci-test
        env:
          NODE_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Run Danger
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
