name: Budgematic CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Run Linter
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
      - name: Run Tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
      - name: Run Danger
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
